apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-angular
  labels:
    app: reverse-angular
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-angular
  template:
    metadata:
      labels:
        app: reverse-angular
        tier: backend
    spec:
      containers:
        - name: reverse-angular
          image: project3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-angular
  name: reverse-angular-service
spec:
  ports:
    - port: 70
      targetPort: 80
  selector:
    app: reverse-angular
