apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reverse-angular-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: reverse-angular
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70